import React, { useState } from 'react';
import { ResumeAnalysisResult } from '../types/resume';
import { Download, Copy, Check, Printer, X, FileText } from 'lucide-react';

interface ExportReportModalProps {
  analysis: ResumeAnalysisResult;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ analysis, onClose }) => {
  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    return `# ResuPulse AI - Comprehensive Resume & CV Analysis Report

**Candidate Name:** ${analysis.candidateProfile.name}
**Detected Title:** ${analysis.candidateProfile.detectedTitle}
**Seniority Level:** ${analysis.candidateProfile.seniorityLevel} (${analysis.candidateProfile.yearsOfExperienceInferred})
**Candidate Archetype:** ${analysis.candidateProfile.candidateArchetype}
**Core Superpower:** ${analysis.candidateProfile.coreSuperpower}
**Analyzed Date:** ${new Date(analysis.analyzedAt).toLocaleDateString()}
**File Analyzed:** ${analysis.pdfFileName}

---

## 1. Executive Scoring Summary
- **Overall Facility Score:** ${analysis.overallScore} / 100
- **Overall Grade:** ${analysis.overallGrade}
- **ATS Parsability Index:** ${analysis.atsParsabilityScore} %
- **Candidate Percentile Rank:** Top ${100 - analysis.pitAnalysis.percentileRank}% (Rank: ${analysis.pitAnalysis.percentileRank}th percentile)

### Executive Summary:
${analysis.candidateProfile.executiveSummary}

---

## 2. Six-Facility Grading Breakdown
1. **Impact & Metrics:** ${analysis.facilityScores.impact.score}/100 - ${analysis.facilityScores.impact.verdict}
2. **ATS Compatibility:** ${analysis.facilityScores.atsFormatting.score}/100 - ${analysis.facilityScores.atsFormatting.verdict}
3. **Skills Alignment:** ${analysis.facilityScores.skillsRelevance.score}/100 - ${analysis.facilityScores.skillsRelevance.verdict}
4. **Brevity & Conciseness:** ${analysis.facilityScores.brevity.score}/100 - ${analysis.facilityScores.brevity.verdict}
5. **Career Progression:** ${analysis.facilityScores.progression.score}/100 - ${analysis.facilityScores.progression.verdict}
6. **Visual & Design Polish:** ${analysis.facilityScores.visualHierarchy.score}/100 - ${analysis.facilityScores.visualHierarchy.verdict}

---

## 3. "The Pit" Benchmark Comparison
${analysis.pitAnalysis.benchmarkComparisons
  .map(
    (b) => `### ${b.name} (${b.tier}): ${b.score}/100 - ${b.status}
- **Recruiter Feedback:** ${b.feedback}
- **Checklist:**
${b.keyRequirementChecks.map((c) => `  * [${c.passed ? 'X' : ' '}] ${c.name}`).join('\n')}`
  )
  .join('\n\n')}

### Critical Red Flags & Pitfalls Flagged:
${analysis.pitAnalysis.redFlagsAndPitfalls
  .map(
    (rf) => `* **[${rf.severity.toUpperCase()} SEVERITY] ${rf.title}:** ${rf.description}
  - Found: "${rf.locationOrExample}"
  - Fix: ${rf.fixAdvice}`
  )
  .join('\n\n')}

---

## 4. Prompt Refinement & Bullet Point Rewrites
${analysis.weakBulletPoints
  .map(
    (bp, idx) => `### Bullet Point ${idx + 1} (${bp.section})
- **Original:** "${bp.original}"
- **Critique:** ${bp.critique}
- **Google XYZ Formula Rewrite:** "${bp.optimizedVersions.xyzFormula}"
- **Quantified Metrics Rewrite:** "${bp.optimizedVersions.quantified}"
- **Executive Leadership Rewrite:** "${bp.optimizedVersions.executive}"
- **Concise Version:** "${bp.optimizedVersions.concise}"`
  )
  .join('\n\n')}

---

## 5. Career Strategy & Interview Armor
### Predicted Interview Questions:
${analysis.careerStrategy.probableInterviewQuestions
  .map(
    (q, i) => `${i + 1}. **"${q.question}"**
   - *Why they ask:* ${q.reasonWhyAsked}
   - *Talking point:* ${q.suggestedTalkingPoint}`
  )
  .join('\n\n')}

### Suggested LinkedIn Headline:
"${analysis.careerStrategy.suggestedLinkedInHeadline}"

*Report generated by ResuPulse AI - Direct Multimodal PDF Analysis Engine.*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = () => {
    const element = document.createElement('a');
    const file = new Blob([generateMarkdown()], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `${analysis.candidateProfile.name.replace(/\s+/g, '_')}_Resume_Analysis.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-700 rounded-3xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 bg-slate-800/90 border-b border-slate-700 flex items-center justify-between">
          <div className="flex items-center space-x-2.5">
            <div className="p-2 rounded-xl bg-indigo-500/20 text-indigo-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white">Full Resume Evaluation Report</h3>
              <p className="text-xs text-slate-400">
                {analysis.candidateProfile.name} • {analysis.pdfFileName}
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center space-x-1 px-3 py-1.5 rounded-xl bg-slate-700 hover:bg-slate-600 text-xs font-semibold text-slate-200 transition"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
            </button>
            <button
              onClick={handleDownloadFile}
              className="flex items-center space-x-1 px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-xs font-semibold text-white transition shadow-sm"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download .MD</span>
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center space-x-1 px-3 py-1.5 rounded-xl bg-slate-700 hover:bg-slate-600 text-xs font-semibold text-slate-200 transition"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-white hover:bg-slate-700 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Viewer */}
        <div className="flex-1 p-6 overflow-y-auto bg-slate-950 font-mono text-xs text-slate-300 leading-relaxed whitespace-pre-wrap selection:bg-indigo-500/30">
          {generateMarkdown()}
        </div>
      </div>
    </div>
  );
};
